Add erdos_to_ros operator with success and failure tests.
erdos-project/erdos pull request #147
Opened 2020-11-25 03:20 UTC by shreyask23

Created a new tests directory under erdos/python for python tests. Added erdos_to_ros operator with success and failure tests. The operator converts erdos messages to ros messages and publishes them.

2020-11-25 22:37 UTC, sukritkalra commented on python/tests/erdos_to_ros_test.py
> +    def __init__(self, publish_stream, ros_msg_type, rostopic, node_name, func):
Can we name the function to `conversion_func` from `func`?

Also, we should probably move the order of these arguments around.

2021-02-12 18:16 UTC, sukritkalra requested changes
@shreyask23 The operators need to be renamed and move to a proper location in the module instead of the tests.

@pschafhalter Can you take a look? and where do you think we should move the operators to?

2021-02-12 18:16 UTC, sukritkalra commented on python/tests/erdos_to_ros_test.py
> +                                       queue_size=10)
The `queue_size` should not be set to a default since its choice has repercussions on the performance.

2021-02-26 22:37 UTC, pschafhalter commented
Operators should be move into `python/erdos/operators/`.

I'll take a closer look once @sukritkalra's comments are addressed.

2022-01-17 20:04 UTC, sukritkalra commented
Closing because #188 was merged.

2022-01-17 20:04 UTC, closed without merging