[Python] Update docs for operators and streams
erdos-project/erdos pull request #204
Opened 2022-02-08 21:09 UTC by objorkman

2022-02-09 19:54 UTC, objorkman commented
I need to make some fixes to the other files, looks like the paths aren't working for the doctests

2022-02-10 01:12 UTC, pschafhalter requested changes
Could you make sure that the pythondoc tests pass? You might need to add `erdos.internal` to the mock modules listed here:
https://github.com/erdos-project/erdos/blob/3b1235a8274bfe84accef03f24da97c8caa679d6/python/doc/source/conf.py#L49

2022-02-10 01:12 UTC, pschafhalter commented on python/doc/source/operators.rst
> +ERDOS operators process received data, and use streams to broadcast Messages
Could you link to the `Message` and `WatermarkMessage` classes?

2022-02-10 01:12 UTC, pschafhalter commented on python/doc/source/operators.rst
> +by ordering callbacks in an ERDOS-managed execution lattice, which serves as a
```suggestion
via a system-managed ordering of callbacks, which is implemented as a
```

2022-02-10 01:12 UTC, pschafhalter commented on python/doc/source/operators.rst
> +Operators are structures which implement a certain communication pattern. For example,
Could you add that operators are implemented as classes, and must subclass the built-in operator type that specifies its communication pattern?

Also, describe the different types of communication patterns (Source, Sink, OneInOneOut, etc) in an unordered list

2022-02-10 01:12 UTC, pschafhalter commented on python/doc/source/streams.rst
> +Operators receive data by reading messages from Read Streams.
Could you link to the ReadStream class?

2022-02-10 01:12 UTC, pschafhalter commented on python/doc/source/streams.rst
> +Operators receive data by reading messages from Read Streams.
Operators also receive data by implementing callbacks that are automatically invoked upon the receipt of a message.

2022-02-17 00:55 UTC, pschafhalter commented
Closing this PR and continuing work on #206

2022-02-17 00:55 UTC, closed without merging